name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/requirements-test.txt

    - name: Check with Black Code Formatter
      run: |
        black custom_components/husqvarna_automower_map --check
    - name: Lint with pydocstyle
      run: |
        pydocstyle custom_components/husqvarna_automower_map
    - name: Lint with isort
      run: |
        isort custom_components/husqvarna_automower_map
